server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.106.180.210:3306/ertai?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  jpa:
    database: mysql

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.qf.pojo
logging:
  level:
      com.qf.dao: debug
